5th-6th_semester/market/cart/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

5th-6th_semester/market/goods/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.product_list, name='product_list'),
    re_path(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]

5th-6th_semester/market/market/urls.py
from django.urls import include, re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    re_path(r'^orders/', include(('orders.urls', 'orders'), namespace='orders')),
    re_path(r'^', include(('goods.urls', 'goods'), namespace='goods')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

5th-6th_semester/market/orders/urls.py
from django.urls import re_path
from . import views


urlpatterns = [
    re_path(r'^create/$', views.order_create, name='order_create'),
]

5th-6th_semester/market/cart/models.py
from django.db import models

# Create your models here.

5th-6th_semester/market/goods/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, db_index=True, unique=True, verbose_name='URL')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('goods:product_list_by_category',
                        args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, verbose_name='Категория')
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, db_index=True, verbose_name='URL')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name='Фото')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    stock = models.PositiveIntegerField(verbose_name='Количество')
    available = models.BooleanField(default=True, verbose_name='В наличии')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('goods:product_detail',
                        args=[self.id, self.slug])

5th-6th_semester/market/orders/models.py
from django.db import models
from goods.models import Product

class Order(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    email = models.EmailField(verbose_name='Почта')
    address = models.CharField(max_length=250, verbose_name='Адрес')
    postal_code = models.CharField(max_length=20, verbose_name='Почтовый индекс')
    city = models.CharField(max_length=100, verbose_name='Город')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False, verbose_name='Оплачено')

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE, verbose_name='Товар')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

5th-6th_semester/market/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Количество')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

5th-6th_semester/market/orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

5th-6th_semester/market/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from goods.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')
    
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')
    
def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

5th-6th_semester/market/goods/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'goods/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})
                   
def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request,
                  'goods/product/detail.html',
                  {'product': product})
                  
def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'goods/product/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})

5th-6th_semester/market/orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # очистка корзины
            cart.clear()
            return render(request, 'orders/order/created.html',
                          {'order': order})
    else:
        form = OrderCreateForm
    return render(request, 'orders/order/create.html',
                  {'cart': cart, 'form': form})

5th-6th_semester/market/cart/templates/cart/detail.html
{% extends "goods/base.html" %}
{% load static %}
{% block title %}
    Ваша корзина
{% endblock %}

{% block content %}
    <h1>Ваша корзина</h1>
    <table class="cart-table">
        <thead>
        <tr>
            <th>Фото</th>
            <th>Название</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Цена</th>
            <th>Общая цена</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <div style="width:100px; height:100px; overflow: hidden;">
								<img style="height:100px" src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static "img/no_image.png" %}
                                {% endif %}">
							</div>
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url "cart:cart_remove" product.id%}">Удалить</a></td>
                    <td class="num">{{ item.price }}р</td>
                    <td class="num">{{ item.total_price }}р</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Итого</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }}р</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "goods:product_list" %}" class="button light">Продолжить покупки</a>
        <a href="{% url "orders:order_create" %}" class="button">
			Оформить заказ
		</a>
    </p>
	<style>#content{margin-left:5px; margin-top:40px;}
	th {padding-right:20px}
	td {padding-right:20px}</style>
{% endblock %}

5th-6th_semester/market/goods/templates/goods/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock %}</title>
	{% block head %}
	{% endblock %}
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
<nav>
	<div class="logo">
		<a href="/">Техномаркет</a>
	</div>
	<div class="cart">
		{% with total_items=cart|length %}
			{% if cart|length > 0 %}
				Корзина:
				<a href="{% url "cart:cart_detail" %}">
					Товаров: {{ total_items }},
					На сумму {{ cart.get_total_price }}р
				</a>
			{% else %}
				Корзина пуста
			{% endif %}
		{% endwith %}
	</div>
</nav>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

5th-6th_semester/market/goods/templates/goods/product/detail.html
{% extends "goods/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block head %}
    <link href="{% static "css/details.css" %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="product-detail">
        <img style="width: 300px" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">{{ product.price }}р</p>
        {{ product.description|linebreaks }}
    </div>
	
	<form action="{% url "cart:cart_add" product.id %}" method="post">
		{{ cart_product_form }}
		{% csrf_token %}
		<input type="submit" value="В корзину">
	</form>
	<style>#content{margin-left:5px; margin-top:40px}</style>
{% endblock %}

5th-6th_semester/market/goods/templates/goods/product/list.html
{% extends "goods/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Техномаркет{% endif %}
{% endblock %}
{% block head %}
    <link href="{% static "css/list.css" %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="sidebar">
        <h3>Категории</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "goods:product_list" %}">Все</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Все товары{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <div style="width:200px; height:200px; overflow: hidden; text-align:center;">
						<img style="height:200px" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
					</div>
				</a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                {{ product.price }}р
            </div>
        {% endfor %}
    </div>
{% endblock %}

5th-6th_semester/market/orders/templates/orders/order/create.html
{% extends "goods/base.html" %}
{% block title %}Checkout{% endblock %}
{% block content %}
	<h1>Оформление заказа</h1>
    <div class="order-info">
        <h3>Ваш заказ</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>{{ item.total_price }}р</span>
                </li>
            {% endfor %}
        </ul>
        <p>Цена: {{ cart.get_total_price }}р</p>
    </div>
    <form action="." method="post" class="order-form">
        {{ form.as_p }}
        <p><input type="submit" value="Оформить заказ"></p>
        {% csrf_token %}
    </form>
	<style>#content{margin-left:5px; margin-top:40px}</style>
{% endblock %}

5th-6th_semester/market/orders/templates/orders/order/created.html
{% extends "goods/base.html" %}

{% block title %}Спасибо!{% endblock %}

{% block content %}
    <h1>Спасибо!</h1>
    <p>Ваш заказ успешно оформлен. Номер вашего заказа
        <strong>{{ order.id }}</strong>.</p>
	<p>Ожидайте, когда продавец свяжется с вами по почте.</p>
	<style>#content{margin-left:5px; margin-top:40px}</style>
{% endblock %}